General:
  project_name: Force-EMG-Fatigue
  project_dir: F:/Codes/MachineLearningProject
  data_dir: F:/Codes/MachineLearningProject/data
  neptune: False
  neptune_model: False

  data_filename: False
Data:
  fs: 2048
Training:
  window_size: 512
  stride: 10
  batch_size: 1024
  epochs: 50
  device: cuda
  lambda: 100
  LR: 0.001
Model:

Visualization:
  figsize: [10, 5]
  font_label:
    size: 12
    fontproperties: Times New Roman
  font_title:
    size: 20
    fontproperties: Times New Roman
